/**
 * Frozen dictionaries used by the legacy v3 Essence Crafting permalink codec.
 *
 * These values were captured from the legacy bundled augment master used when
 * v3 links were emitted. Their positions are part of that wire format. Do not
 * regenerate them from current published data: inserting a sorted name would
 * silently change the meaning of existing links.
 */
export const LEGACY_V3_AUGMENT_NAMES = [
  'A History of Draconic Interference',
  'A Legendary History of Draconic Interference',
  'A Treatise on Battle',
  'Arrowbound Topaz',
  'Aspect of Tar',
  'Bestiary of the Planes',
  "Black Sands' Desire",
  'Brightbane Emerald',
  'Brightclaw',
  'Brightfang',
  'Brighthorn',
  'Brightscale',
  'Bronzescale',
  'Citrene of Greater Dragonmarks',
  'Claw: Acid Spell Crit Damage',
  'Claw: Assassinate',
  'Claw: Cold Spell Crit Damage',
  'Claw: Electric Spell Crit Damage',
  'Claw: Fire Spell Crit Damage',
  'Claw: Force Spell Crit Damage',
  'Claw: Light Spell Crit Damage',
  'Claw: Magical Resistance Rating',
  'Claw: Magical Resistance Rating',
  'Claw: Negative Spell Crit Damage',
  'Claw: Physical Resistance Rating',
  'Claw: Positive Spell Crit Damage',
  'Claw: Repair Spell Crit Damage',
  'Claw: Sonic Spell Crit Damage',
  'Claw: Stunning',
  'Claw: Sunder',
  'Claw: Trip',
  'Clearwater Diamond',
  'Coalescent Ruby',
  'Crystallized Drop of Tea',
  'Crystallized Unicorn Tear',
  'Deconstructor',
  'Demonheart Emerald',
  'Diamond of Balance +10',
  'Diamond of Balance +13',
  'Diamond of Balance +15',
  'Diamond of Balance +17',
  'Diamond of Balance +18',
  'Diamond of Balance +19',
  'Diamond of Balance +20',
  'Diamond of Balance +5',
  'Diamond of Bluff +10',
  'Diamond of Bluff +13',
  'Diamond of Bluff +15',
  'Diamond of Bluff +17',
  'Diamond of Bluff +18',
  'Diamond of Bluff +19',
  'Diamond of Bluff +20',
  'Diamond of Bluff +5',
  'Diamond of Charisma +1',
  'Diamond of Charisma +11',
  'Diamond of Charisma +12',
  'Diamond of Charisma +14',
  'Diamond of Charisma +3',
  'Diamond of Charisma +5',
  'Diamond of Charisma +6',
  'Diamond of Charisma +8',
  'Diamond of Charisma +9',
  'Diamond of Concentration +10',
  'Diamond of Concentration +13',
  'Diamond of Concentration +15',
  'Diamond of Concentration +17',
  'Diamond of Concentration +18',
  'Diamond of Concentration +19',
  'Diamond of Concentration +20',
  'Diamond of Concentration +5',
  'Diamond of Constitution +1',
  'Diamond of Constitution +11',
  'Diamond of Constitution +12',
  'Diamond of Constitution +14',
  'Diamond of Constitution +3',
  'Diamond of Constitution +5',
  'Diamond of Constitution +6',
  'Diamond of Constitution +8',
  'Diamond of Constitution +9',
  'Diamond of Dexterity +1',
  'Diamond of Dexterity +11',
  'Diamond of Dexterity +12',
  'Diamond of Dexterity +14',
  'Diamond of Dexterity +3',
  'Diamond of Dexterity +5',
  'Diamond of Dexterity +6',
  'Diamond of Dexterity +8',
  'Diamond of Dexterity +9',
  'Diamond of Diplomacy +10',
  'Diamond of Diplomacy +13',
  'Diamond of Diplomacy +15',
  'Diamond of Diplomacy +17',
  'Diamond of Diplomacy +18',
  'Diamond of Diplomacy +19',
  'Diamond of Diplomacy +20',
  'Diamond of Diplomacy +5',
  'Diamond of Disable Device +10',
  'Diamond of Disable Device +13',
  'Diamond of Disable Device +15',
  'Diamond of Disable Device +17',
  'Diamond of Disable Device +18',
  'Diamond of Disable Device +19',
  'Diamond of Disable Device +20',
  'Diamond of Disable Device +5',
  'Diamond of Exceptional Charisma +1',
  'Diamond of Exceptional Constitution +1',
  'Diamond of Exceptional Dexterity +1',
  'Diamond of Exceptional Intelligence +1',
  'Diamond of Exceptional Strength +1',
  'Diamond of Exceptional Wisdom +1',
  'Diamond of Festive Charisma +2',
  'Diamond of Festive Constitution +2',
  'Diamond of Festive Dexterity +2',
  'Diamond of Festive Intelligence +2',
  'Diamond of Festive Strength +2',
  'Diamond of Festive Wisdom +2',
  'Diamond of Haggle +10',
  'Diamond of Haggle +13',
  'Diamond of Haggle +15',
  'Diamond of Haggle +17',
  'Diamond of Haggle +18',
  'Diamond of Haggle +19',
  'Diamond of Haggle +20',
  'Diamond of Haggle +5',
  'Diamond of Heal +10',
  'Diamond of Heal +13',
  'Diamond of Heal +15',
  'Diamond of Heal +17',
  'Diamond of Heal +18',
  'Diamond of Heal +19',
  'Diamond of Heal +20',
  'Diamond of Heal +5',
  'Diamond of Hide +10',
  'Diamond of Hide +13',
  'Diamond of Hide +15',
  'Diamond of Hide +17',
  'Diamond of Hide +18',
  'Diamond of Hide +19',
  'Diamond of Hide +20',
  'Diamond of Hide +5',
  'Diamond of Insightful Charisma +5',
  'Diamond of Insightful Constitution +5',
  'Diamond of Insightful Dexterity +5',
  'Diamond of Insightful Intelligence +5',
  'Diamond of Insightful Strength +5',
  'Diamond of Insightful Wisdom +5',
  'Diamond of Intelligence +1',
  'Diamond of Intelligence +11',
  'Diamond of Intelligence +12',
  'Diamond of Intelligence +14',
  'Diamond of Intelligence +3',
  'Diamond of Intelligence +5',
  'Diamond of Intelligence +6',
  'Diamond of Intelligence +8',
  'Diamond of Intelligence +9',
  'Diamond of Intimidate +10',
  'Diamond of Intimidate +13',
  'Diamond of Intimidate +15',
  'Diamond of Intimidate +17',
  'Diamond of Intimidate +18',
  'Diamond of Intimidate +19',
  'Diamond of Intimidate +20',
  'Diamond of Intimidate +5',
  'Diamond of Jump +10',
  'Diamond of Jump +13',
  'Diamond of Jump +15',
  'Diamond of Jump +17',
  'Diamond of Jump +18',
  'Diamond of Jump +19',
  'Diamond of Jump +20',
  'Diamond of Jump +5',
  'Diamond of Listen +10',
  'Diamond of Listen +13',
  'Diamond of Listen +15',
  'Diamond of Listen +17',
  'Diamond of Listen +18',
  'Diamond of Listen +19',
  'Diamond of Listen +20',
  'Diamond of Listen +5',
  'Diamond of Move Silently +10',
  'Diamond of Move Silently +13',
  'Diamond of Move Silently +15',
  'Diamond of Move Silently +17',
  'Diamond of Move Silently +18',
  'Diamond of Move Silently +19',
  'Diamond of Move Silently +20',
  'Diamond of Move Silently +5',
  'Diamond of Open Lock +10',
  'Diamond of Open Lock +13',
  'Diamond of Open Lock +15',
  'Diamond of Open Lock +17',
  'Diamond of Open Lock +18',
  'Diamond of Open Lock +19',
  'Diamond of Open Lock +20',
  'Diamond of Open Lock +5',
  'Diamond of Perform +10',
  'Diamond of Perform +13',
  'Diamond of Perform +15',
  'Diamond of Perform +17',
  'Diamond of Perform +18',
  'Diamond of Perform +19',
  'Diamond of Perform +20',
  'Diamond of Perform +5',
  'Diamond of Repair +10',
  'Diamond of Repair +13',
  'Diamond of Repair +15',
  'Diamond of Repair +17',
  'Diamond of Repair +18',
  'Diamond of Repair +19',
  'Diamond of Repair +20',
  'Diamond of Repair +5',
  'Diamond of Search +10',
  'Diamond of Search +13',
  'Diamond of Search +15',
  'Diamond of Search +17',
  'Diamond of Search +18',
  'Diamond of Search +19',
  'Diamond of Search +20',
  'Diamond of Search +5',
  'Diamond of Spellcraft +10',
  'Diamond of Spellcraft +13',
  'Diamond of Spellcraft +15',
  'Diamond of Spellcraft +17',
  'Diamond of Spellcraft +18',
  'Diamond of Spellcraft +19',
  'Diamond of Spellcraft +20',
  'Diamond of Spellcraft +5',
  'Diamond of Spot +10',
  'Diamond of Spot +13',
  'Diamond of Spot +15',
  'Diamond of Spot +17',
  'Diamond of Spot +18',
  'Diamond of Spot +19',
  'Diamond of Spot +20',
  'Diamond of Spot +5',
  'Diamond of Strength +1',
  'Diamond of Strength +11',
  'Diamond of Strength +12',
  'Diamond of Strength +14',
  'Diamond of Strength +3',
  'Diamond of Strength +5',
  'Diamond of Strength +6',
  'Diamond of Strength +8',
  'Diamond of Strength +9',
  'Diamond of Swim +10',
  'Diamond of Swim +13',
  'Diamond of Swim +15',
  'Diamond of Swim +17',
  'Diamond of Swim +18',
  'Diamond of Swim +19',
  'Diamond of Swim +20',
  'Diamond of Swim +5',
  'Diamond of the Magi',
  'Diamond of Tumble +10',
  'Diamond of Tumble +13',
  'Diamond of Tumble +15',
  'Diamond of Tumble +17',
  'Diamond of Tumble +18',
  'Diamond of Tumble +19',
  'Diamond of Tumble +20',
  'Diamond of Tumble +5',
  'Diamond of Vitality +20',
  'Diamond of Wisdom +1',
  'Diamond of Wisdom +11',
  'Diamond of Wisdom +12',
  'Diamond of Wisdom +14',
  'Diamond of Wisdom +3',
  'Diamond of Wisdom +5',
  'Diamond of Wisdom +6',
  'Diamond of Wisdom +8',
  'Diamond of Wisdom +9',
  'Dimensional Horn',
  'Dismagicka',
  'Dolorous Acid (ML:34)',
  'Dolorous Arcana: Acid (ML:34)',
  'Dolorous Arcana: Acid (ML:8)',
  'Dolorous Arcana: Cold (ML:34)',
  'Dolorous Arcana: Cold (ML:8)',
  'Dolorous Arcana: Electric (ML:34)',
  'Dolorous Arcana: Electric (ML:8)',
  'Dolorous Arcana: Fire (ML:34)',
  'Dolorous Arcana: Fire (ML:8)',
  'Dolorous Arcana: Force (ML:34)',
  'Dolorous Arcana: Force (ML:8)',
  'Dolorous Arcana: Light (ML:34)',
  'Dolorous Arcana: Light (ML:8)',
  'Dolorous Arcana: Negative (ML:34)',
  'Dolorous Arcana: Negative (ML:8)',
  'Dolorous Arcana: Positive (ML:34)',
  'Dolorous Arcana: Positive (ML:8)',
  'Dolorous Arcana: Repair (ML:34)',
  'Dolorous Arcana: Repair (ML:8)',
  'Dolorous Arcana: Sonic (ML:34)',
  'Dolorous Arcana: Sonic (ML:8)',
  'Dolorous Chill (ML:34)',
  'Dolorous Dimlight (ML:34)',
  'Dolorous Flames (ML:34)',
  'Dolorous Focus (ML:34)',
  'Dolorous Invigorator (ML:34)',
  'Dolorous Invigorator (ML:8)',
  'Dolorous Shadows (ML:34)',
  'Dolorous Silencer (ML:34)',
  'Dolorous Silencer (ML:8)',
  'Dolorous Sparks (ML:34)',
  'Dolorous Voidwheel (ML:34)',
  'Dolorous Voidwheel (ML:8)',
  'Dolorous: Accuracy (ML:34)',
  'Dolorous: Accuracy (ML:8)',
  'Dolorous: Acid Spell Crit Damage (ML:34)',
  'Dolorous: Acid Spell Crit Damage (ML:8)',
  'Dolorous: Cold Spell Crit Damage (ML:34)',
  'Dolorous: Cold Spell Crit Damage (ML:8)',
  'Dolorous: Damage (ML:34)',
  'Dolorous: Damage (ML:8)',
  'Dolorous: Deception (ML:34)',
  'Dolorous: Deception (ML:8)',
  'Dolorous: Electric Spell Crit Damage (ML:34)',
  'Dolorous: Electric Spell Crit Damage (ML:8)',
  'Dolorous: Fire Spell Crit Damage (ML:34)',
  'Dolorous: Fire Spell Crit Damage (ML:8)',
  'Dolorous: Force Spell Crit Damage (ML:34)',
  'Dolorous: Force Spell Crit Damage (ML:8)',
  'Dolorous: Healing Amplification (ML:34)',
  'Dolorous: Healing Amplification (ML:8)',
  'Dolorous: Light Spell Crit Damage (ML:34)',
  'Dolorous: Light Spell Crit Damage (ML:8)',
  'Dolorous: Negative Amplification (ML:34)',
  'Dolorous: Negative Amplification (ML:8)',
  'Dolorous: Negative Spell Crit Damage (ML:34)',
  'Dolorous: Negative Spell Crit Damage (ML:8)',
  'Dolorous: Positive Spell Crit Damage (ML:34)',
  'Dolorous: Positive Spell Crit Damage (ML:8)',
  'Dolorous: Quality Accuracy (ML:34)',
  'Dolorous: Quality Accuracy (ML:8)',
  'Dolorous: Quality Charisma (ML:34)',
  'Dolorous: Quality Charisma (ML:8)',
  'Dolorous: Quality Combat Mastery (ML:34)',
  'Dolorous: Quality Combat Mastery (ML:8)',
  'Dolorous: Quality Constitution (ML:34)',
  'Dolorous: Quality Constitution (ML:8)',
  'Dolorous: Quality Damage (ML:34)',
  'Dolorous: Quality Damage (ML:8)',
  'Dolorous: Quality Dexterity (ML:34)',
  'Dolorous: Quality Dexterity (ML:8)',
  'Dolorous: Quality Intelligence (ML:34)',
  'Dolorous: Quality Intelligence (ML:8)',
  'Dolorous: Quality Strength (ML:34)',
  'Dolorous: Quality Strength (ML:8)',
  'Dolorous: Quality Wisdom (ML:34)',
  'Dolorous: Quality Wisdom (ML:8)',
  'Dolorous: Repair Amplification (ML:34)',
  'Dolorous: Repair Amplification (ML:8)',
  'Dolorous: Repair Spell Crit Damage (ML:34)',
  'Dolorous: Repair Spell Crit Damage (ML:8)',
  'Dolorous: Seeker (ML:34)',
  'Dolorous: Seeker (ML:8)',
  'Dolorous: Sonic Spell Crit Damage (ML:34)',
  'Dolorous: Sonic Spell Crit Damage (ML:8)',
  'Draconic Soul Gem',
  'Dreadful Acid (ML:8)',
  'Dreadful Arcana (ML:8)',
  'Dreadful Chill (ML:8)',
  'Dreadful Flames (ML:8)',
  'Dreadful Sparks (ML:8)',
  'Emerald of Arcane Empowerment',
  'Emerald of Bitter Wounds',
  'Emerald of Eldritch Empowerment',
  'Emerald of Greater Rage',
  'Emerald of Greater Smiting',
  'Emerald of Vile Empowerment',
  'Encyclopedia of the Dead, Vol. 1',
  'Encyclopedia of the Dead, Vol. 3',
  'Essence of Constellation, Broken and Reforged',
  'Essence of Dark Diversion',
  'Essence of the Champion of the Twins',
  'Essence of the Cloak of Strahd',
  'Essence of the Cobalt Guard',
  'Essence of the Cracked Core',
  'Essence of the Dethek Runestone',
  'Essence of the Epic Litany of the Dead',
  'Essence of The Masque',
  'Essence of the Nullscale Armor',
  'Essence of the Spear of the Mournlands',
  'Essence of Ultimatum',
  'Facet of Coalesced Impacts',
  'Facet of Condensed Power',
  'Facet of Psionic Intrusion',
  'Fang: Accuracy',
  'Fang: Acid Spell Crit Damage',
  'Fang: Cold Spell Crit Damage',
  'Fang: Damage',
  'Fang: Deception',
  'Fang: Electric Spell Crit Damage',
  'Fang: Fire Spell Crit Damage',
  'Fang: Force Spell Crit Damage',
  'Fang: Healing Amplification',
  'Fang: Light Spell Crit Damage',
  'Fang: Negative Amplification',
  'Fang: Negative Spell Crit Damage',
  'Fang: Positive Spell Crit Damage',
  'Fang: Repair Amplification',
  'Fang: Repair Spell Crit Damage',
  'Fang: Seeker',
  'Fang: Sonic Spell Crit Damage',
  'Feareater',
  'Flameclaw',
  'Flamefang',
  'Flamehorn',
  'Flamescale',
  'Fossilized Amber',
  'Fragment of Extraplanar Alignment',
  'Fragment of Extraplanar Shadow',
  'Globe of Cursed Blood',
  'Globe of Imperial Blood',
  'Globe of True Imperial Blood',
  'Goldfang',
  'Goldscale',
  "Golem's Heart",
  'Guide to Animal Handling',
  'Horn: Armor Piercing',
  'Horn: Armor Piercing',
  'Horn: Enhanced Ghostly',
  'Horn: Profane DCs',
  'Horn: Relentless Fury',
  'Horn: Resistance',
  'Horn: Sacred DCs',
  'How To Cast Fast',
  'How To Cast Faster',
  'Iceclaw',
  'Icefang',
  'Icehorn',
  'Icescale',
  'Iridiscent Claw: Acid',
  'Iridiscent Claw: Cold',
  'Iridiscent Claw: Electric',
  'Iridiscent Claw: Fire',
  'Iridiscent Claw: Force',
  'Iridiscent Claw: Light',
  'Iridiscent Claw: Negative',
  'Iridiscent Claw: Positive',
  'Iridiscent Claw: Repair',
  'Iridiscent Claw: Sonic',
  'Iridiscent Fang',
  'Iridiscent Scale',
  'Legendary Arrowbound Topaz',
  'Legendary Bestiary of the Planes',
  'Legendary Brightbane Emerald',
  'Legendary Coalescent Ruby',
  'Legendary Demonheart Emerald',
  'Legendary Guide to Animal Handling',
  'Legendary Moment to Legendary Moment',
  'Legendary Ruby of Acid Blast',
  'Legendary Ruby of Flaming Blast',
  'Legendary Ruby of Icy Blast',
  "Legendary Ruby of Implement's Acid",
  "Legendary Ruby of Implement's Flame",
  "Legendary Ruby of Implement's Frost",
  "Legendary Ruby of Implement's Wind",
  'Legendary Ruby of Shocking Blast',
  'Legendary Sapphire of Riposte',
  'Legendary Silvertongue Sapphire',
  'Legendary Swordcrossed Topaz',
  'Legendary Undying Sapphire',
  'Legendary Wraithborn Emerald',
  'Lifetaker',
  'Lunar Gem of Abjuration (Heroic)',
  'Lunar Gem of Abjuration (Legendary)',
  'Lunar Gem of Accuracy (Heroic)',
  'Lunar Gem of Accuracy (Legendary)',
  'Lunar Gem of Balance and Tumble (Heroic)',
  'Lunar Gem of Balance and Tumble (Legendary)',
  'Lunar Gem of Blast Dice (Heroic)',
  'Lunar Gem of Blast Dice (Heroic)',
  'Lunar Gem of Charisma (Heroic)',
  'Lunar Gem of Charisma (Legendary)',
  'Lunar Gem of Conjuration (Heroic)',
  'Lunar Gem of Conjuration (Heroic)',
  'Lunar Gem of Constitution (Heroic)',
  'Lunar Gem of Constitution (Legendary)',
  'Lunar Gem of Dexterity (Heroic)',
  'Lunar Gem of Dexterity (Legendary)',
  'Lunar Gem of Disable Device and Open Lock (Heroic)',
  'Lunar Gem of Disable Device and Open Lock (Legendary)',
  'Lunar Gem of Enchantment (Heroic)',
  'Lunar Gem of Enchantment (Legendary)',
  'Lunar Gem of Haggle and Perform (Heroic)',
  'Lunar Gem of Haggle and Perform (Heroic)',
  'Lunar Gem of Haggle and Perform (Legendary)',
  'Lunar Gem of Haggle and Perform (Legendary)',
  'Lunar Gem of Healing Amplification (Heroic)',
  'Lunar Gem of Healing Amplification (Legendary)',
  'Lunar Gem of Illusion (Heroic)',
  'Lunar Gem of Illusion (Legendary)',
  'Lunar Gem of Intelligence (Heroic)',
  'Lunar Gem of Intelligence (Legendary)',
  'Lunar Gem of Jump and Swim (Heroic)',
  'Lunar Gem of Jump and Swim (Legendary)',
  'Lunar Gem of Linguistics (Heroic)',
  'Lunar Gem of Linguistics (Legendary)',
  'Lunar Gem of Magical Protection (Epic)',
  'Lunar Gem of Magical Protection (Heroic)',
  'Lunar Gem of Magical Protection (Legendary)',
  'Lunar Gem of Melee Power (Heroic)',
  'Lunar Gem of Melee Power (Legendary)',
  'Lunar Gem of Natural Armor (Heroic)',
  'Lunar Gem of Natural Armor (Legendary)',
  'Lunar Gem of Necromancy (Heroic)',
  'Lunar Gem of Necromancy (Legendary)',
  'Lunar Gem of Negative Amplification (Heroic)',
  'Lunar Gem of Negative Healing Amplification (Legendary)',
  'Lunar Gem of Pact Dice (Herioc)',
  'Lunar Gem of Pact Dice (Legendary)',
  'Lunar Gem of Peace (Heroic)',
  'Lunar Gem of Peace (Legendary)',
  'Lunar Gem of Physical Protection (Heroic)',
  'Lunar Gem of Physical Protection (Legendary)',
  'Lunar Gem of Ranged Power (Heroic)',
  'Lunar Gem of Ranged Power (Legendary)',
  'Lunar Gem of Repair Amplification (Heroic)',
  'Lunar Gem of Repair Amplification (Legendary)',
  'Lunar Gem of Search and Spot (Heroic)',
  'Lunar Gem of Search and Spot (Legendary)',
  'Lunar Gem of Spell Difficulty (Epic)',
  'Lunar Gem of Spell Difficulty (Heroic)',
  'Lunar Gem of Spell Difficulty (Legendary)',
  'Lunar Gem of Spellpower (Epic)',
  'Lunar Gem of Spellpower (Heroic)',
  'Lunar Gem of Spellpower (Legendary)',
  'Lunar Gem of Strength (Heroic)',
  'Lunar Gem of Strength (Legendary)',
  'Lunar Gem of Swift Charging (Heroic)',
  'Lunar Gem of Swift Charging (Legendary)',
  'Lunar Gem of Transmutation (Heroic)',
  'Lunar Gem of Transmutation (Legendary)',
  'Lunar Gem of Weapon Damage (Heroic)',
  'Lunar Gem of Weapon Damage (Legendary)',
  'Lunar Gem of Wisdom (Heroic)',
  'Lunar Gem of Wisdom (Legendary)',
  'Melancholic Acid (ML:34)',
  'Melancholic Acid (ML:8)',
  'Melancholic Arcana (ML:34)',
  'Melancholic Arcana (ML:8)',
  'Melancholic Booster (ML:34)',
  'Melancholic Booster (ML:8)',
  'Melancholic Chill (ML:34)',
  'Melancholic Chill (ML:8)',
  'Melancholic Converter (ML:34)',
  'Melancholic Converter (ML:8)',
  'Melancholic Device (ML:34)',
  'Melancholic Device (ML:8)',
  'Melancholic Dimlight (ML:34)',
  'Melancholic Dimlight (ML:8)',
  'Melancholic Flames (ML:34)',
  'Melancholic Flames (ML:8)',
  'Melancholic Plating (ML:34)',
  'Melancholic Plating (ML:8)',
  'Melancholic Shadows (ML:34)',
  'Melancholic Shadows (ML:8)',
  'Melancholic Sparks (ML:34)',
  'Melancholic Sparks (ML:8)',
  'Melancholic: Acid Spell Crit Damage (ML:34)',
  'Melancholic: Acid Spell Crit Damage (ML:8)',
  'Melancholic: Charisma (ML:34)',
  'Melancholic: Charisma (ML:8)',
  'Melancholic: Cold Spell Crit Damage (ML:34)',
  'Melancholic: Cold Spell Crit Damage (ML:8)',
  'Melancholic: Constitution (ML:34)',
  'Melancholic: Constitution (ML:34)',
  'Melancholic: Dexterity (ML:34)',
  'Melancholic: Dexterity (ML:8)',
  'Melancholic: Doubleshot (ML:34)',
  'Melancholic: Doubleshot (ML:8)',
  'Melancholic: Doublestrike (ML:34)',
  'Melancholic: Doublestrike (ML:8)',
  'Melancholic: Electric Spell Crit Damage (ML:34)',
  'Melancholic: Electric Spell Crit Damage (ML:8)',
  'Melancholic: False Life (ML:34)',
  'Melancholic: False Life (ML:8)',
  'Melancholic: Fire Spell Crit Damage (ML:34)',
  'Melancholic: Fire Spell Crit Damage (ML:8)',
  'Melancholic: Force Spell Crit Damage (ML:34)',
  'Melancholic: Force Spell Crit Damage (ML:8)',
  'Melancholic: Intelligence (ML:34)',
  'Melancholic: Intelligence (ML:8)',
  'Melancholic: Light Spell Crit Damage (ML:34)',
  'Melancholic: Light Spell Crit Damage (ML:8)',
  'Melancholic: Negative Spell Crit Damage (ML:34)',
  'Melancholic: Negative Spell Crit Damage (ML:8)',
  'Melancholic: Positive Spell Crit Damage (ML:34)',
  'Melancholic: Positive Spell Crit Damage (ML:8)',
  'Melancholic: Repair Spell Crit Damage (ML:34)',
  'Melancholic: Repair Spell Crit Damage (ML:8)',
  'Melancholic: Sonic Spell Crit Damage (ML:34)',
  'Melancholic: Sonic Spell Crit Damage (ML:8)',
  'Melancholic: Strength (ML:34)',
  'Melancholic: Strength (ML:8)',
  'Melancholic: Wisdom (ML:34)',
  'Melancholic: Wisdom (ML:8)',
  'Meltclaw',
  'Meltfang',
  'Melthorn',
  'Meltscale',
  'Meridian Fragment',
  'Meteoric Star Ruby',
  'Miserable Acid (ML:34)',
  'Miserable Acid (ML:8)',
  'Miserable Arcana: Acid (ML:34)',
  'Miserable Arcana: Acid (ML:8)',
  'Miserable Arcana: Cold (ML:34)',
  'Miserable Arcana: Cold (ML:8)',
  'Miserable Arcana: Electric (ML:34)',
  'Miserable Arcana: Electric (ML:8)',
  'Miserable Arcana: Fire (ML:34)',
  'Miserable Arcana: Fire (ML:8)',
  'Miserable Arcana: Force (ML:34)',
  'Miserable Arcana: Force (ML:8)',
  'Miserable Arcana: Light (ML:34)',
  'Miserable Arcana: Light (ML:8)',
  'Miserable Arcana: Negative (ML:34)',
  'Miserable Arcana: Negative (ML:8)',
  'Miserable Arcana: Positive (ML:34)',
  'Miserable Arcana: Positive (ML:8)',
  'Miserable Arcana: Repair (ML:34)',
  'Miserable Arcana: Repair (ML:8)',
  'Miserable Arcana: Sonic (ML:34)',
  'Miserable Arcana: Sonic (ML:8)',
  'Miserable Armor-Piercing (ML:34)',
  'Miserable Armor-Piercing (ML:8)',
  'Miserable Chill (ML:34)',
  'Miserable Chill (ML:8)',
  'Miserable Destruction (ML:8)',
  'Miserable Dimlight (ML:34)',
  'Miserable Dimlight (ML:8)',
  'Miserable Flames (ML:34)',
  'Miserable Flames (ML:8)',
  'Miserable Humanoid Bane (ML:34)',
  'Miserable Humanoid Bane (ML:8)',
  'Miserable Improved Destruction (ML:34)',
  'Miserable Maiming (ML:34)',
  'Miserable Maiming (ML:8)',
  'Miserable Metalline (ML:34)',
  'Miserable Monstrous Humanoid Bane (ML:34)',
  'Miserable Monstrous Humanoid Bane (ML:8)',
  'Miserable Planar (ML:34)',
  'Miserable Shadows (ML:34)',
  'Miserable Shadows (ML:8)',
  'Miserable Sparks (ML:34)',
  'Miserable Sparks (ML:8)',
  'Miserable Undead Bane (ML:34)',
  'Miserable Undead Bane (ML:8)',
  'Miserable Vermin Bane (ML:34)',
  'Miserable Vermin Bane (ML:8)',
  'Miserable: Acid Spell Crit Chance (ML:34)',
  'Miserable: Acid Spell Crit Damage (ML:34)',
  'Miserable: Acid Spell Crit Damage (ML:8)',
  'Miserable: Assassinate (ML:34)',
  'Miserable: Assassinate (ML:8)',
  'Miserable: Cold Spell Crit Chance (ML:34)',
  'Miserable: Cold Spell Crit Damage (ML:34)',
  'Miserable: Cold Spell Crit Damage (ML:8)',
  'Miserable: Electric Spell Crit Chance (ML:34)',
  'Miserable: Electric Spell Crit Damage (ML:34)',
  'Miserable: Electric Spell Crit Damage (ML:8)',
  'Miserable: Fire Spell Crit Chance (ML:34)',
  'Miserable: Fire Spell Crit Damage (ML:34)',
  'Miserable: Fire Spell Crit Damage (ML:8)',
  'Miserable: Force Absorption (ML:34)',
  'Miserable: Force Spell Crit Chance (ML:34)',
  'Miserable: Force Spell Crit Damage (ML:34)',
  'Miserable: Force Spell Crit Damage (ML:8)',
  'Miserable: Legendary Armor Piercing (ML:34)',
  'Miserable: Light Spell Crit Chance (ML:34)',
  'Miserable: Light Spell Crit Damage (ML:34)',
  'Miserable: Light Spell Crit Damage (ML:8)',
  'Miserable: Magical Resistance Rating (ML:34)',
  'Miserable: Magical Resistance Rating (ML:8)',
  'Miserable: Negative Spell Crit Chance (ML:34)',
  'Miserable: Negative Spell Crit Damage (ML:34)',
  'Miserable: Negative Spell Crit Damage (ML:8)',
  'Miserable: Physical Resistance Rating (ML:34)',
  'Miserable: Physical Resistance Rating (ML:8)',
  'Miserable: Positive Spell Crit Chance (ML:34)',
  'Miserable: Positive Spell Crit Damage (ML:34)',
  'Miserable: Positive Spell Crit Damage (ML:8)',
  'Miserable: Rebellion (ML:34)',
  'Miserable: Repair Spell Crit Chance (ML:34)',
  'Miserable: Repair Spell Crit Damage (ML:34)',
  'Miserable: Repair Spell Crit Damage (ML:8)',
  'Miserable: Sonic Spell Crit Chance (ML:34)',
  'Miserable: Sonic Spell Crit Damage (ML:34)',
  'Miserable: Sonic Spell Crit Damage (ML:8)',
  'Miserable: Spell Penetration (ML:34)',
  'Miserable: Spell Penetration (ML:8)',
  'Miserable: Stunning (ML:34)',
  'Miserable: Stunning (ML:8)',
  'Miserable: Sunder (ML:34)',
  'Miserable: Sunder (ML:8)',
  'Miserable: Trip (ML:34)',
  'Miserable: Trip (ML:8)',
  'Moment to Moment',
  "Ravil's Book of Legendary Recipes",
  "Ravil's Book of Recipes",
  'Ruby Eye of Erosion',
  'Ruby Eye of Force',
  'Ruby Eye of Righteousness',
  'Ruby Eye of the Glacier',
  'Ruby Eye of the Inferno',
  'Ruby Eye of the Tempest',
  'Ruby of Acid (1d6)',
  'Ruby of Acid (2d6)',
  'Ruby of Acid (3d6)',
  'Ruby of Acid (4d6)',
  'Ruby of Acid (5d6)',
  'Ruby of Acid (6d6)',
  'Ruby of Acid (7d6)',
  'Ruby of Acid (8d6)',
  'Ruby of Acid (9d6)',
  'Ruby of Acid Blast',
  'Ruby of Adamantine Arms',
  'Ruby of Chaos',
  'Ruby of Combustion 111',
  'Ruby of Combustion 125',
  'Ruby of Combustion 139',
  'Ruby of Combustion 153',
  'Ruby of Combustion 38',
  'Ruby of Combustion 55',
  'Ruby of Combustion 70',
  'Ruby of Combustion 84',
  'Ruby of Combustion 97',
  'Ruby of Corrosion 111',
  'Ruby of Corrosion 125',
  'Ruby of Corrosion 139',
  'Ruby of Corrosion 153',
  'Ruby of Corrosion 38',
  'Ruby of Corrosion 55',
  'Ruby of Corrosion 70',
  'Ruby of Corrosion 84',
  'Ruby of Corrosion 97',
  'Ruby of Devotion 111',
  'Ruby of Devotion 125',
  'Ruby of Devotion 139',
  'Ruby of Devotion 153',
  'Ruby of Devotion 38',
  'Ruby of Devotion 55',
  'Ruby of Devotion 70',
  'Ruby of Devotion 84',
  'Ruby of Devotion 97',
  'Ruby of Disintegration',
  'Ruby of Evil',
  'Ruby of Fey Bane',
  'Ruby of Flame (1d6)',
  'Ruby of Flame (2d6)',
  'Ruby of Flame (3d6)',
  'Ruby of Flame (4d6)',
  'Ruby of Flame (5d6)',
  'Ruby of Flame (6d6)',
  'Ruby of Flame (7d6)',
  'Ruby of Flame (8d6)',
  'Ruby of Flame (9d6)',
  'Ruby of Flaming Blast',
  'Ruby of Frost (1d6)',
  'Ruby of Frost (2d6)',
  'Ruby of Frost (3d6)',
  'Ruby of Frost (4d6)',
  'Ruby of Frost (5d6)',
  'Ruby of Frost (6d6)',
  'Ruby of Frost (7d6)',
  'Ruby of Frost (8d6)',
  'Ruby of Frost (9d6)',
  'Ruby of Ghostbane',
  'Ruby of Glaciation 111',
  'Ruby of Glaciation 125',
  'Ruby of Glaciation 139',
  'Ruby of Glaciation 153',
  'Ruby of Glaciation 38',
  'Ruby of Glaciation 55',
  'Ruby of Glaciation 70',
  'Ruby of Glaciation 84',
  'Ruby of Glaciation 97',
  'Ruby of Good',
  'Ruby of Icy Blast',
  "Ruby of Implement's Acid",
  "Ruby of Implement's Flame",
  "Ruby of Implement's Frost",
  "Ruby of Implement's Wind",
  'Ruby of Impulse 111',
  'Ruby of Impulse 125',
  'Ruby of Impulse 139',
  'Ruby of Impulse 153',
  'Ruby of Impulse 38',
  'Ruby of Impulse 55',
  'Ruby of Impulse 70',
  'Ruby of Impulse 84',
  'Ruby of Impulse 97',
  'Ruby of Iron Blows',
  'Ruby of Magnetism 111',
  'Ruby of Magnetism 125',
  'Ruby of Magnetism 139',
  'Ruby of Magnetism 153',
  'Ruby of Magnetism 38',
  'Ruby of Magnetism 55',
  'Ruby of Magnetism 70',
  'Ruby of Magnetism 84',
  'Ruby of Magnetism 97',
  'Ruby of Nullification 111',
  'Ruby of Nullification 125',
  'Ruby of Nullification 139',
  'Ruby of Nullification 153',
  'Ruby of Nullification 38',
  'Ruby of Nullification 55',
  'Ruby of Nullification 70',
  'Ruby of Nullification 84',
  'Ruby of Nullification 97',
  'Ruby of Order',
  'Ruby of Radiance 111',
  'Ruby of Radiance 125',
  'Ruby of Radiance 139',
  'Ruby of Radiance 153',
  'Ruby of Radiance 38',
  'Ruby of Radiance 55',
  'Ruby of Radiance 70',
  'Ruby of Radiance 84',
  'Ruby of Radiance 97',
  'Ruby of Reconstruction 111',
  'Ruby of Reconstruction 125',
  'Ruby of Reconstruction 139',
  'Ruby of Reconstruction 153',
  'Ruby of Reconstruction 38',
  'Ruby of Reconstruction 55',
  'Ruby of Reconstruction 70',
  'Ruby of Reconstruction 84',
  'Ruby of Reconstruction 97',
  'Ruby of Resonance 111',
  'Ruby of Resonance 125',
  'Ruby of Resonance 139',
  'Ruby of Resonance 153',
  'Ruby of Resonance 38',
  'Ruby of Resonance 55',
  'Ruby of Resonance 70',
  'Ruby of Resonance 84',
  'Ruby of Resonance 97',
  'Ruby of Shock (1d6)',
  'Ruby of Shock (2d6)',
  'Ruby of Shock (3d6)',
  'Ruby of Shock (4d6)',
  'Ruby of Shock (5d6)',
  'Ruby of Shock (6d6)',
  'Ruby of Shock (7d6)',
  'Ruby of Shock (8d6)',
  'Ruby of Shock (9d6)',
  'Ruby of Shocking Blast',
  'Ruby of Silvered Strikes',
  'Ruby of the Adamantine Blessing',
  'Ruby of the Endless Night',
  'Ruby of The Gatekeepers',
  'Ruby of the Iron Hand',
  'Ruby of the Snowpeaks',
  'Ruby of the Surging Tide',
  'Ruby of the Vampire Slayer',
  'Sapphire of Accuracy +10',
  'Sapphire of Accuracy +12',
  'Sapphire of Accuracy +15',
  'Sapphire of Accuracy +17',
  'Sapphire of Accuracy +2',
  'Sapphire of Accuracy +20',
  'Sapphire of Accuracy +22',
  'Sapphire of Accuracy +5',
  'Sapphire of Accuracy +8',
  'Sapphire of Armored Agility +1',
  'Sapphire of Armored Agility +2',
  'Sapphire of Crushing Wave Guard',
  'Sapphire of Defense +12',
  'Sapphire of Defense +16',
  'Sapphire of Defense +20',
  'Sapphire of Defense +24',
  'Sapphire of Defense +28',
  'Sapphire of Defense +3',
  'Sapphire of Defense +32',
  'Sapphire of Defense +36',
  'Sapphire of Defense +8',
  'Sapphire of Dodge +1%',
  'Sapphire of Dodge +11%',
  'Sapphire of Dodge +12%',
  'Sapphire of Dodge +14%',
  'Sapphire of Dodge +3%',
  'Sapphire of Dodge +5%',
  'Sapphire of Dodge +6%',
  'Sapphire of Dodge +8%',
  'Sapphire of Dodge +9%',
  'Sapphire of False Life +12',
  'Sapphire of False Life +18',
  'Sapphire of False Life +24',
  'Sapphire of False Life +30',
  'Sapphire of False Life +36',
  'Sapphire of False Life +4',
  'Sapphire of False Life +42',
  'Sapphire of False Life +48',
  'Sapphire of False Life +54',
  'Sapphire of Good Luck +1',
  'Sapphire of Good Luck +2',
  'Sapphire of Good Luck +3',
  'Sapphire of Greater Heroism',
  'Sapphire of Healing Amplification +11',
  'Sapphire of Healing Amplification +18',
  'Sapphire of Healing Amplification +24',
  'Sapphire of Healing Amplification +3',
  'Sapphire of Healing Amplification +31',
  'Sapphire of Healing Amplification +37',
  'Sapphire of Healing Amplification +44',
  'Sapphire of Healing Amplification +50',
  'Sapphire of Healing Amplification +57',
  'Sapphire of Heavy Fortification',
  'Sapphire of Heroism',
  'Sapphire of Light Fortification',
  'Sapphire of Moderate Fortification',
  'Sapphire of Natural Armor +1',
  'Sapphire of Natural Armor +11',
  'Sapphire of Natural Armor +12',
  'Sapphire of Natural Armor +14',
  'Sapphire of Natural Armor +3',
  'Sapphire of Natural Armor +5',
  'Sapphire of Natural Armor +6',
  'Sapphire of Natural Armor +8',
  'Sapphire of Natural Armor +9',
  'Sapphire of Negative Amplification +11',
  'Sapphire of Negative Amplification +18',
  'Sapphire of Negative Amplification +24',
  'Sapphire of Negative Amplification +3',
  'Sapphire of Negative Amplification +31',
  'Sapphire of Negative Amplification +37',
  'Sapphire of Negative Amplification +44',
  'Sapphire of Negative Amplification +50',
  'Sapphire of Negative Amplification +57',
  'Sapphire of Protection +1',
  'Sapphire of Protection +10',
  'Sapphire of Protection +11',
  'Sapphire of Protection +3',
  'Sapphire of Protection +4',
  'Sapphire of Protection +5',
  'Sapphire of Protection +6',
  'Sapphire of Protection +8',
  'Sapphire of Protection +9',
  'Sapphire of Repair Amplification +11',
  'Sapphire of Repair Amplification +18',
  'Sapphire of Repair Amplification +24',
  'Sapphire of Repair Amplification +3',
  'Sapphire of Repair Amplification +31',
  'Sapphire of Repair Amplification +37',
  'Sapphire of Repair Amplification +44',
  'Sapphire of Repair Amplification +50',
  'Sapphire of Repair Amplification +57',
  'Sapphire of Resistance +1',
  'Sapphire of Resistance +10',
  'Sapphire of Resistance +11',
  'Sapphire of Resistance +3',
  'Sapphire of Resistance +4',
  'Sapphire of Resistance +5',
  'Sapphire of Resistance +6',
  'Sapphire of Resistance +8',
  'Sapphire of Resistance +9',
  'Sapphire of Riposte',
  'Sapphire of Shatter +11',
  'Sapphire of Shatter +12',
  'Sapphire of Shatter +14',
  'Sapphire of Shatter +16',
  'Sapphire of Shatter +2',
  'Sapphire of Shatter +4',
  'Sapphire of Shatter +6',
  'Sapphire of Shatter +7',
  'Sapphire of Shatter +9',
  'Sapphire of Snowpeaks Speed',
  'Sapphire of Spell Agility +10%',
  'Sapphire of Spell Agility +15%',
  'Sapphire of Spell Agility +5%',
  'Sapphire of Stunning +11',
  'Sapphire of Stunning +12',
  'Sapphire of Stunning +14',
  'Sapphire of Stunning +16',
  'Sapphire of Stunning +2',
  'Sapphire of Stunning +4',
  'Sapphire of Stunning +6',
  'Sapphire of Stunning +7',
  'Sapphire of Stunning +9',
  'Sapphire of Vertigo +11',
  'Sapphire of Vertigo +12',
  'Sapphire of Vertigo +14',
  'Sapphire of Vertigo +16',
  'Sapphire of Vertigo +2',
  'Sapphire of Vertigo +4',
  'Sapphire of Vertigo +6',
  'Sapphire of Vertigo +7',
  'Sapphire of Vertigo +9',
  'Scale: Acid Spell Crit Damage',
  'Scale: Charisma',
  'Scale: Cold Spell Crit Damage',
  'Scale: Constitution',
  'Scale: Dexterity',
  'Scale: Electric Spell Crit Damage',
  'Scale: False Life',
  'Scale: Fire Spell Crit Damage',
  'Scale: Force Spell Crit Damage',
  'Scale: Intelligence',
  'Scale: Light Spell Crit Damage',
  'Scale: Negative Spell Crit Damage',
  'Scale: Positive Spell Crit Damage',
  'Scale: Repair Spell Crit Damage',
  'Scale: Sonic Spell Crit Damage',
  'Scale: Strength',
  'Scale: Wisdom',
  'Scourge of the Outsiders',
  'Set Augment: Alluring Elocution',
  'Set Augment: Arcane Barrier',
  'Set Augment: Arcane Guardian',
  'Set Augment: Bold Tactician',
  'Set Augment: Brutal Blows',
  'Set Augment: Cruel Cut',
  'Set Augment: Cunning Impact',
  'Set Augment: Dusk Raider',
  'Set Augment: Esoterica',
  'Set Augment: Imbued Infusion',
  'Set Augment: Legendary Bulwark',
  'Set Augment: Paragon Guard',
  'Set Augment: Perfect Silence',
  'Set Augment: Piercing Mind',
  'Set Augment: Quickblade',
  'Set Augment: Subtle Blade',
  'Set Augment: Touch of Power',
  'Set Augment: Tough Shields',
  'Set Augment: Truthful Blow',
  'Set Augment: Visions of the Beyond',
  'Set Augment: Wild Fortitude',
  'Set Bonus: Deacon of the Auricular Sacrarium',
  'Set Bonus: Defender of Tanaroa',
  'Set Bonus: Devotion of the Firemouth',
  'Set Bonus: Dread Stalker',
  'Set Bonus: Echoes of the Walking Ancestors',
  "Set Bonus: The Legendary Dread Isle's Curse",
  'Shadowcale',
  'Shadowclaw',
  'Shadowfang',
  'Shadowhorn',
  'Silverfang',
  'Silverscale',
  'Silvertongue Sapphire',
  'Solar Gem of Abjuration (Heroic)',
  'Solar Gem of Abjuration (Heroic)',
  'Solar Gem of Arcane Endurance (Legendary)',
  'Solar Gem of Arcane Endurance (Legendary)',
  'Solar Gem of Armor Layers (Heroic)',
  'Solar Gem of Armor Layers (Legendary)',
  'Solar Gem of Assassination (Heroic)',
  'Solar Gem of Assassination (Legendary)',
  'Solar Gem of Attack (Heroic)',
  'Solar Gem of Attack (Legendary)',
  'Solar Gem of Balance and Tumble (Heroic)',
  'Solar Gem of Balance and Tumble (Legendary)',
  'Solar Gem of Blast Dice (Heroic)',
  'Solar Gem of Blast Dice (Heroic)',
  'Solar Gem of Charisma (Epic)',
  'Solar Gem of Charisma (Heroic)',
  'Solar Gem of Charisma (Legendary)',
  'Solar Gem of Constitution (Epic)',
  'Solar Gem of Constitution (Heroic)',
  'Solar Gem of Constitution (Legendary)',
  'Solar Gem of Cruelty (Heroic)',
  'Solar Gem of Cruelty (Legendary)',
  'Solar Gem of Dexterity (Epic)',
  'Solar Gem of Dexterity (Heroic)',
  'Solar Gem of Dexterity (Legendary)',
  'Solar Gem of Disable Device and Open Lock (Heroic)',
  'Solar Gem of Disable Device and Open Lock (Heroic)',
  'Solar Gem of Disable Device and Open Lock (Legendary)',
  'Solar Gem of Disable Device and Open Lock (Legendary)',
  'Solar Gem of Dodge (Epic)',
  'Solar Gem of Dodge (Heroic)',
  'Solar Gem of Dodge (Legendary)',
  'Solar Gem of Doubleshot (Heroic)',
  'Solar Gem of Doubleshot (Legendary)',
  'Solar Gem of Doublestrike (Epic)',
  'Solar Gem of Doublestrike (Heroic)',
  'Solar Gem of Doublestrike (Legendary)',
  'Solar Gem of Elemental Absorption (Heroic)',
  'Solar Gem of Elemental Absorption (Legendary)',
  'Solar Gem of Enduring (Heroic)',
  'Solar Gem of Enduring (Legendary)',
  'Solar Gem of Force Absorption (Heroic)',
  'Solar Gem of Force Absorption (Legendary)',
  'Solar Gem of Fortification Bypass (Epic)',
  'Solar Gem of Fortification Bypass (Heroic)',
  'Solar Gem of Fortification Bypass (Legendary)',
  'Solar Gem of Fortitude (Heroic)',
  'Solar Gem of Fortitude (Legendary)',
  'Solar Gem of Haggle and Perform (Heroic)',
  'Solar Gem of Haggle and Perform (Heroic)',
  'Solar Gem of Haggle and Perform (Legendary)',
  'Solar Gem of Haggle and Perform (Legendary)',
  'Solar Gem of Healing Amplification (Heroic)',
  'Solar Gem of Healing Amplification (Legendary)',
  'Solar Gem of Imbuement (Epic)',
  'Solar Gem of Imbuement (Heroic)',
  'Solar Gem of Imbuement (Legendary)',
  'Solar Gem of Intelligence (Epic)',
  'Solar Gem of Intelligence (Heroic)',
  'Solar Gem of Intelligence (Legendary)',
  'Solar Gem of Linguistics (Heroic)',
  'Solar Gem of Linguistics (Legendary)',
  'Solar Gem of Magical Resistance Rating (Heroic)',
  'Solar Gem of Magical Resistance Rating (Legendary)',
  'Solar Gem of Melee Power (Heroic)',
  'Solar Gem of Melee Power (Legendary)',
  'Solar Gem of MRR Cap (Heroic)',
  'Solar Gem of MRR Cap (Legendary)',
  'Solar Gem of Necromancy (Heroic)',
  'Solar Gem of Necromancy (Legendary)',
  'Solar Gem of Negative Amplification (Heroic)',
  'Solar Gem of Negative Amplification (Legendary)',
  'Solar Gem of Pact Dice (Herioc)',
  'Solar Gem of Pact Dice (Herioc)',
  'Solar Gem of Physical Resistance Rating (Heroic)',
  'Solar Gem of Physical Resistance Rating (Legendary)',
  'Solar Gem of Ranged Power (Heroic)',
  'Solar Gem of Ranged Power (Legendary)',
  'Solar Gem of Reflex (Epic)',
  'Solar Gem of Reflex (Heroic)',
  'Solar Gem of Reflex (Legendary)',
  'Solar Gem of Repair Amplification (Heroic)',
  'Solar Gem of Repair Amplification (Legendary)',
  'Solar Gem of Rune Arm DCs (Heroic)',
  'Solar Gem of Rune Arm DCs (Legendary)',
  'Solar Gem of Sneak Attack Damage (Heroic)',
  'Solar Gem of Sneak Attack Damage (Legendary)',
  'Solar Gem of Sneak Attack Dice (Heroic)',
  'Solar Gem of Sneak Attack Dice (Legendary)',
  'Solar Gem of Spell Critical Chance (Epic)',
  'Solar Gem of Spell Critical Chance (Heroic)',
  'Solar Gem of Spell Critical Chance (Legendary)',
  'Solar Gem of Spell Critical Damage (Heroic)',
  'Solar Gem of Spell Critical Damage (Legendary)',
  'Solar Gem of Spell DCs (Heroic)',
  'Solar Gem of Spell DCs (Legendary)',
  'Solar Gem of Spell Penetration (Heroic)',
  'Solar Gem of Spell Penetration (Legendary)',
  'Solar Gem of Spellpower (Heroic)',
  'Solar Gem of Spellpower (Legendary)',
  'Solar Gem of Strength (Epic)',
  'Solar Gem of Strength (Heroic)',
  'Solar Gem of Strength (Legendary)',
  'Solar Gem of Strikethrough (Epic)',
  'Solar Gem of Strikethrough (Heroic)',
  'Solar Gem of Strikethrough (Legendary)',
  'Solar Gem of Swift Charging (Heroic)',
  'Solar Gem of Swift Charging (Legendary)',
  'Solar Gem of Tactical DCs (Epic)',
  'Solar Gem of Tactical DCs (Heroic)',
  'Solar Gem of Tactical DCs (Legendary)',
  'Solar Gem of Threat Decrease (Heroic)',
  'Solar Gem of Threat Decrease (Legendary)',
  'Solar Gem of Threat Increase (Heroic)',
  'Solar Gem of Threat Increase (Legendary)',
  'Solar Gem of Will (Heroic)',
  'Solar Gem of Will (Legendary)',
  'Solar Gem of Wisdom (Epic)',
  'Solar Gem of Wisdom (Heroic)',
  'Solar Gem of Wisdom (Legendary)',
  'Sparkclaw',
  'Sparkfang',
  'Sparkhorn',
  'Sparkscale',
  "Storm's Bulwark",
  'Swordcrossed Topaz',
  'The Art of Persuasion, Vol. 1',
  'The Art of Persuasion, Vol. 3',
  'The Art of Sabotage, Vol. 1',
  'The Art of Sabotage, Vol. 3',
  'The Blackstone Liturgy',
  'The Book of Defense: Fortitude',
  'The Book of Defense: Reflexes',
  'The Book of Defense: Willpower',
  'The Eye of Daanvi',
  'The Eye of Dolurrh',
  'The Eye of Lamannia',
  'The Eye of Mabar',
  'The Eye of Shavarath',
  'The Finite Limits of Construction',
  'The Infinite Limits of Construction',
  'The Legendary Book of Defense: Fortitude',
  'The Legendary Book of Defense: Reflexes',
  'The Legendary Book of Defense: Willpower',
  "The Master's Gift",
  'Topaz of Abjuration',
  'Topaz of Abjuration Power',
  'Topaz of Acid Resistance 10',
  'Topaz of Acid Resistance 15',
  'Topaz of Acid Resistance 20',
  'Topaz of Acid Resistance 25',
  'Topaz of Acid Resistance 30',
  'Topaz of Acid Resistance 35',
  'Topaz of Acid Resistance 40',
  'Topaz of Acid Resistance 45',
  'Topaz of Acid Resistance 5',
  'Topaz of Anthem',
  'Topaz of Augment Summoning',
  'Topaz of Blindness Immunity',
  'Topaz of Cold Resistance 10',
  'Topaz of Cold Resistance 15',
  'Topaz of Cold Resistance 20',
  'Topaz of Cold Resistance 25',
  'Topaz of Cold Resistance 30',
  'Topaz of Cold Resistance 35',
  'Topaz of Cold Resistance 40',
  'Topaz of Cold Resistance 45',
  'Topaz of Cold Resistance 5',
  'Topaz of Conjuration',
  'Topaz of Conjured Power',
  'Topaz of Damage +1',
  'Topaz of Damage +10',
  'Topaz of Damage +11',
  'Topaz of Damage +3',
  'Topaz of Damage +4',
  'Topaz of Damage +5',
  'Topaz of Damage +6',
  'Topaz of Damage +8',
  'Topaz of Damage +9',
  'Topaz of Deathblock',
  'Topaz of Electric Resistance 10',
  'Topaz of Electric Resistance 15',
  'Topaz of Electric Resistance 20',
  'Topaz of Electric Resistance 25',
  'Topaz of Electric Resistance 30',
  'Topaz of Electric Resistance 35',
  'Topaz of Electric Resistance 40',
  'Topaz of Electric Resistance 45',
  'Topaz of Electric Resistance 5',
  'Topaz of Enchanted Power',
  'Topaz of Enchantment',
  'Topaz of Evocation',
  'Topaz of Evocation Power',
  'Topaz of Fear Immunity',
  'Topaz of Feather Falling',
  'Topaz of Fire Resistance 10',
  'Topaz of Fire Resistance 15',
  'Topaz of Fire Resistance 20',
  'Topaz of Fire Resistance 25',
  'Topaz of Fire Resistance 30',
  'Topaz of Fire Resistance 35',
  'Topaz of Fire Resistance 40',
  'Topaz of Fire Resistance 45',
  'Topaz of Fire Resistance 5',
  'Topaz of Greater Abjuration',
  'Topaz of Greater Conjuration',
  'Topaz of Greater Enchantment',
  'Topaz of Greater Evocation',
  'Topaz of Greater Illusion',
  'Topaz of Greater Necromancy',
  'Topaz of Greater Transmutation',
  'Topaz of Illusion',
  'Topaz of Illusory Power',
  'Topaz of Lesser Dragonmarks',
  'Topaz of Melee Power +10',
  'Topaz of Melee Power +2',
  'Topaz of Melee Power +4',
  'Topaz of Melee Power +6',
  'Topaz of Melee Power +8',
  'Topaz of Minor Rage',
  'Topaz of Minor Smiting',
  'Topaz of Necromancy',
  'Topaz of Necromantic Power',
  'Topaz of Proof Against Disease +3',
  'Topaz of Proof Against Disease +4',
  'Topaz of Proof Against Disease +5',
  'Topaz of Proof Against Disease +6',
  'Topaz of Proof Against Disease +8',
  'Topaz of Proof Against Poison +3',
  'Topaz of Proof Against Poison +4',
  'Topaz of Proof Against Poison +5',
  'Topaz of Proof Against Poison +6',
  'Topaz of Proof Against Poison +8',
  'Topaz of Quick Movements',
  'Topaz of Ranged Power +10',
  'Topaz of Ranged Power +12',
  'Topaz of Ranged Power +2',
  'Topaz of Ranged Power +4',
  'Topaz of Ranged Power +6',
  'Topaz of Ranged Power +8',
  'Topaz of Sonic Resistance 10',
  'Topaz of Sonic Resistance 15',
  'Topaz of Sonic Resistance 20',
  'Topaz of Sonic Resistance 25',
  'Topaz of Sonic Resistance 30',
  'Topaz of Sonic Resistance 35',
  'Topaz of Sonic Resistance 40',
  'Topaz of Sonic Resistance 45',
  'Topaz of Sonic Resistance 5',
  'Topaz of Spell Penetration +1',
  'Topaz of Spell Penetration +2',
  'Topaz of Spell Penetration +3',
  'Topaz of Spell Penetration +4',
  'Topaz of Spell Penetration +5',
  'Topaz of Spell Penetration +6',
  'Topaz of Spell Penetration +7',
  'Topaz of Spell Penetration +9',
  'Topaz of Striding 10%',
  'Topaz of Striding 20%',
  'Topaz of Striding 30%',
  'Topaz of Swiftness 10%',
  'Topaz of Swiftness 15%',
  'Topaz of Swiftness 5%',
  'Topaz of Transmutation',
  'Topaz of Transmuted Power',
  'Topaz of Water Breathing',
  'Topaz of Wizardry +129',
  'Topaz of Wizardry +162',
  'Topaz of Wizardry +19',
  'Topaz of Wizardry +195',
  'Topaz of Wizardry +228',
  'Topaz of Wizardry +261',
  'Topaz of Wizardry +60',
  'Topaz of Wizardry +96',
  'Undying Sapphire',
  'Voidfang',
  'Voidscale',
  'Weaverwisp Melody',
  'Woeful Acid (ML:34)',
  'Woeful Acidburn (ML:34)',
  'Woeful Chill (ML:34)',
  'Woeful Dimlit (ML:34)',
  'Woeful Echoes (ML:34)',
  'Woeful Energy (ML:34)',
  'Woeful Flames (ML:34)',
  'Woeful Frostbite (ML:34)',
  'Woeful Lightning (ML:34)',
  'Woeful Magma (ML:34)',
  'Woeful Salt (ML:34)',
  'Woeful Shadow (ML:34)',
  'Woeful Shadows (ML:34)',
  'Woeful Sparks (ML:34)',
  'Woeful Venom (ML:34)',
  'Woeful: Acid Spell Crit Chance (ML:34)',
  'Woeful: Armor-Piercing (ML:34)',
  'Woeful: Armor-Piercing (ML:8)',
  'Woeful: Cold Spell Crit Chance (ML:34)',
  'Woeful: Electric Spell Crit Chance (ML:34)',
  'Woeful: Enhanced Ghostly (ML:34)',
  'Woeful: Enhanced Ghostly (ML:8)',
  'Woeful: Exception Spell Focus Mastery (ML:34)',
  'Woeful: Fire Spell Crit Chance (ML:34)',
  'Woeful: Force Spell Crit Chance (ML:34)',
  'Woeful: Greater Marksmanship (ML:34)',
  'Woeful: Light Spell Crit Chance (ML:34)',
  'Woeful: Negative Spell Crit Chance (ML:34)',
  'Woeful: Positive Spell Crit Chance (ML:34)',
  'Woeful: Profane DCs (ML:34)',
  'Woeful: Profane DCs (ML:8)',
  'Woeful: Quality Seeker (ML:34)',
  'Woeful: Quality Spell Focus Mastery (ML:34)',
  'Woeful: Relentless Fury (ML:34)',
  'Woeful: Relentless Fury (ML:8)',
  'Woeful: Repair Spell Crit Chance (ML:34)',
  'Woeful: Resistance (ML:34)',
  'Woeful: Resistance (ML:8)',
  'Woeful: Sacred DCs (ML:34)',
  'Woeful: Sacred DCs (ML:8)',
  'Woeful: Sonic Spell Crit Chance (ML:34)',
  'Woeful: Strength of Purpose (ML:34)',
  'Woeful: Wizardry (ML:34)',
  'Woeful: Wizardry (ML:8)',
  'Wraithborn Emerald'
] as const

export const LEGACY_V3_EFFECT_NAMES = [
  '1',
  'Acid',
  'Acid Absorption',
  'Acid Blast',
  'Acid Damage',
  'Acid Resistance',
  'Action Boost Charges',
  'Adamantine',
  'Air Elemental Knockdown Ward',
  'Air Elemental Slow Ward',
  'Alchemical Conservation',
  'Arcane Spell Failure Reduction',
  'Armor Class',
  'Artifact Melee Power',
  'Artifact Ranged Power',
  'Assassin Special Ability DC',
  'Assassinate DC',
  'Attack Rolls',
  'Attack Rolls (Ranged)',
  'Balance Skill',
  'Bane Damage vs Constructs',
  'Bane Damage vs Dragons',
  'Bane Damage vs Fey',
  'Bane Damage vs Magical Beasts',
  'Bane Damage vs Undead',
  'Bane vs Outsiders',
  'Banishing',
  'Bard Song Regeneration',
  'Bitter Frostbite',
  'Bludgeon',
  'Bluff Skill',
  'Charisma',
  'Cold',
  'Cold Absorption',
  'Cold Damage',
  'Cold Resistance',
  'Command +4',
  'Command +7',
  'Concentration Skill',
  'Constitution',
  'Cooldown Reduction: Bluff',
  'Cooldown Reduction: Diplomacy',
  'Cooldown Reduction: Intimidate',
  'Corroding (6d6 On-Crit)',
  'Critical Accuracy',
  'Critical Damage',
  'Curse: Untyped Damage over Time',
  'Damage',
  'Damage (Ranged)',
  'Damage Dice',
  'Damage Reduction Bypass: Adamantine',
  'Damage Reduction Bypass: Alchemical Silver',
  'Damage Reduction Bypass: Byeshk',
  'Damage Reduction Bypass: Chaos',
  'Damage Reduction Bypass: Chaotic',
  'Damage Reduction Bypass: Cold Iron',
  'Damage Reduction Bypass: Crystal',
  'Damage Reduction Bypass: Evil',
  'Damage Reduction Bypass: Good',
  'Damage Reduction Bypass: Lawful',
  'Damage Reduction Bypass: Mithril',
  'Damage Reduction Bypass: Silver',
  'Damage vs Helpless',
  'Deathblock',
  'Demonic Shield',
  'Destruction',
  'Dexterity',
  'Diplomacy Skill',
  'Disable Device Skill',
  'Disintegration',
  'Dodge Chance',
  'Doubleshot Chance',
  'Doublestrike Chance',
  'Eldritch Blast Dice',
  'Electric Absorption',
  'Electric Blast',
  'Electric Damage',
  'Electric Resistance',
  'Electricity',
  'Empower Spell (Cost Reduction)',
  'Enhanced Ghostly',
  'Ethereal',
  'Experience Point Gain',
  'Feat: Augment Summoning',
  'Feat: Quick Draw',
  'Feather Falling',
  'Fire',
  'Fire Absorption',
  'Fire Damage',
  'Fire Resistance',
  'Fire Spell Critical Chance',
  'Flaming (6d6 On-Crit)',
  'Flaming Blast',
  'Force Absorption',
  'Force Damage',
  'Fortification',
  'Fortification Bypass Chance',
  'Fortitude (Disease) Saving Throws',
  'Fortitude Saving Throws',
  'Freezing (6d6 On-Crit)',
  'Ghost Touch',
  'Ghostly',
  'Ghostly (Miss Chance)',
  'Greater Acid Blast',
  'Greater Boon of Undeath',
  'Greater Dragonmark Charges',
  'Greater Flaming Blast',
  'Greater Heroism',
  'Greater Icy Blast',
  'Greater Shocking Blast',
  'Grip of Venom',
  'Haggle Skill',
  'Heal Like a Golem',
  'Heal Skill',
  'Healing Amplification',
  'Heroism',
  'Hide Skill',
  'Holy Damage',
  'Humanoid Bane',
  'Icy Blast',
  'Icy Block',
  'Imbue Dice',
  'Immunity to Mind Altering Enchantments',
  'Immunity: Blindness',
  'Immunity: Fear',
  'Immunity: Knockdown',
  'Immunity: Natural Disease',
  'Immunity: Petrification',
  'Immunity: Slow',
  'Improved Demonic Shield',
  'Improved Destruction',
  'Improved Quelling Strikes',
  'Improved Shattermantle',
  'Inflict Negative Level',
  'Inspire Greatness (song): Physical Resistance Rating',
  'Intelligence',
  'Intimidate Skill',
  'Invisibility Guard',
  'Jolting (6d6 On-Crit)',
  'Jolting 15',
  'Jolting 16',
  'Jump Skill',
  'Law Damage',
  'Law Damage vs non-Lawful Enemies',
  'Legendary Affirmation',
  'Legendary Dripping Magma',
  'Legendary Ice',
  'Legendary Ooze',
  'Legendary Salt',
  'Legendary Vacuum',
  'Lesser Dragonmark Charges',
  'Light Damage',
  'Lightning Lash',
  'Lingering Acidic Burn',
  'Listen Skill',
  'Magic Resistance Rating',
  'Magical Cap Resistance Rating',
  'Magical Resistance',
  'Magical Resistance Rating',
  'Maiming 2',
  'Maiming 7',
  'Material Type: Adamantine',
  'Material Type: Byeshk',
  'Material Type: Cold Iron',
  'Material Type: Crystal',
  'Material Type: Silver',
  'Max Dex Bonus (Armor)',
  'Maximize Spell (Cost Reduction)',
  'Maximum Hit Points',
  'Maximum Spell Points',
  'Melee Alacrity',
  'Melee Attack Speed',
  'Melee Power',
  'Melee Threat Generation',
  'Melee Threat Reduction',
  'Minor Freezing Ice',
  'Monstrous Humanoid Bane',
  'Move Silently Skill',
  'Movement Speed',
  'Negative Amplification',
  'Negative Healing Amplification',
  'Nightmares',
  'Nullmagic Guard',
  'On Critical Hit: Enemy Shaken',
  'Open Lock Skill',
  'Pact Dice',
  'Perform Skill',
  'Physical Resistance',
  'Physical Resistance Rating',
  'Positive Healing',
  'Positive Healing Amplification',
  'Potency',
  'Profane Melee Power',
  'Profane Ranged Power',
  'Proof Against Poison',
  'Quicken Spell (Cost Reduction)',
  'Rage Charges',
  'Ranged Alacrity',
  'Ranged Attack Speed',
  'Ranged Power',
  'Ranged Threat Generation',
  'Ranged Threat Reduction',
  'Reflex Saving Throws',
  'Relentless Fury',
  'Repair Amplification',
  'Repair Skill',
  'Rippling Energy',
  'Rune Arm Focus',
  'Rune Arm Recharge Rate',
  'Runic Revitalization',
  'Rupturing Echo',
  'Rust Damage vs Constructs',
  'Saves (all)',
  'Search Skill',
  'Shatter',
  'Shocking Blast',
  'Slay Living',
  'Slow',
  'Smite Evil Charges',
  'Sneak Attack',
  'Sneak Attack Damage',
  'Sonic Resistance',
  'Soundproof',
  'Spell Cast: Heal',
  'Spell Critical Chance: Acid',
  'Spell Critical Chance: Bludgeoning',
  'Spell Critical Chance: Chaos',
  'Spell Critical Chance: Cold',
  'Spell Critical Chance: Electric',
  'Spell Critical Chance: Evil',
  'Spell Critical Chance: Fire',
  'Spell Critical Chance: Force',
  'Spell Critical Chance: Good',
  'Spell Critical Chance: Lawful',
  'Spell Critical Chance: Light',
  'Spell Critical Chance: Negative Energy',
  'Spell Critical Chance: Piercing',
  'Spell Critical Chance: Poison',
  'Spell Critical Chance: Positive Energy',
  'Spell Critical Chance: Repair',
  'Spell Critical Chance: Rust',
  'Spell Critical Chance: Slashing',
  'Spell Critical Chance: Sonic',
  'Spell Critical Chance: Untyped',
  'Spell Critical Damage: Acid',
  'Spell Critical Damage: Bludgeoning',
  'Spell Critical Damage: Chaos',
  'Spell Critical Damage: Cold',
  'Spell Critical Damage: Electric',
  'Spell Critical Damage: Evil',
  'Spell Critical Damage: Fire',
  'Spell Critical Damage: Force',
  'Spell Critical Damage: Good',
  'Spell Critical Damage: Lawful',
  'Spell Critical Damage: Light',
  'Spell Critical Damage: Negative Energy',
  'Spell Critical Damage: Piercing',
  'Spell Critical Damage: Poison',
  'Spell Critical Damage: Positive Energy',
  'Spell Critical Damage: Repair',
  'Spell Critical Damage: Rust',
  'Spell Critical Damage: Slashing',
  'Spell Critical Damage: Sonic',
  'Spell Critical Damage: Untyped',
  'Spell DC: Abjuration',
  'Spell DC: Breath Weapon',
  'Spell DC: Conjuration',
  'Spell DC: Divination',
  'Spell DC: Enchantment',
  'Spell DC: Evocation',
  'Spell DC: Illusion',
  'Spell DC: Necromancy',
  'Spell DC: Transmutation',
  'Spell Penetration (Level 9)',
  'Spell Point Cost Reduction',
  'Spell Point Multiplier',
  'Spell Power',
  'Spell Power: Acid',
  'Spell Power: Bludgeoning',
  'Spell Power: Chaos',
  'Spell Power: Chaotic',
  'Spell Power: Cold',
  'Spell Power: Electric',
  'Spell Power: Evil',
  'Spell Power: Fire',
  'Spell Power: Force',
  'Spell Power: Good',
  'Spell Power: Lawful',
  'Spell Power: Light',
  'Spell Power: Negative Energy',
  'Spell Power: Piercing',
  'Spell Power: Poison',
  'Spell Power: Positive Energy',
  'Spell Power: Repair',
  'Spell Power: Rust',
  'Spell Power: Slashing',
  'Spell Power: Sonic',
  'Spell Power: Universal',
  'Spell Power: Untyped',
  'Spell Threat Generation',
  'Spell Threat Reduction',
  'Spellcraft Skill',
  'Spot Skill',
  'Strength',
  'Strikethrough Chance',
  'Swim Skill',
  'Tactical DC: Improved Sunder',
  'Tactical DC: Improved Trip',
  'Tactical DC: Stunning',
  'Tactical DC: Sunder',
  'Tactical DC: Trip',
  'Tactical DCs',
  'Temporary Hit Points',
  'Touch of the Mournlands',
  'Tumble Skill',
  'Unarmed Damage',
  'Unconscious Range',
  'Undead Bane',
  'Untyped Curse',
  'Untyped Damage',
  'Use Magic Device Skill',
  'Vampirism',
  'Vermin Bane',
  'Water Breathing',
  'Weapon Alignment: Lawful',
  'Weapon: Ghost Touch',
  'Weapon: Implement',
  'Wild Empathy Charges',
  'Will Saving Throws',
  'Wisdom'
] as const
