blank_issues_enabled: false
contact_links:
  - name: 📣 General Discussion / Feedback
    url: https://github.com/veteran-software/yourddo/discussions
    about: For open-ended questions, ideas, or non-bug feedback, please use GitHub Discussions.
