name: "UI/UX Feedback"
description: Share thoughts on the design, usability, or layout
title: "[UI] <brief description>"
labels: [ feedback, ui ]
body:
  - type: textarea
    id: feedback
    attributes:
      label: What would you like to see improved?
      placeholder: "The fonts are hard to read on dark backgrounds..."
    validations:
      required: true
  - type: dropdown
    id: device-type
    attributes:
      label: Device Type
      options:
        - Desktop
        - Tablet
        - Mobile
        - Other
  - type: textarea
    id: suggestions
    attributes:
      label: Suggestions or Visual References
      description: Share examples or mockups if possible.
